server:
  port: 5000

springdoc:
  swagger-ui:
    path: /api/docs
logging:
  level:
    web: debug

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
    generate-ddl: true

  h2:
    console:
      enabled: true
      path: /h2-ui
